### ISSUE TITLE
Generate trajectories in existing scences

### ISSUE THREAD

**Issue by QC625** [metadriverse/trafficgen#20]
Which script should I run if I want to generate trajectories in existing scenes(already preprocessed)？

**Comment by Alan-LanFeng** [comment]
There is no such script currently. However, you can modify the config parameters if you want to do this. Pull the latest commit and change 'context_num' in the config to 32. Then you can generate trajectories in existing scenes. 'context_num' means 'How many existing vehicles' we want to keep unchanged during generation. The maximum vehicle number in trafficgen is 32.
