### ISSUE TITLE
could you share the model for the step:Generate new traffic scenarios

### ISSUE THREAD

**Issue by xuarehere** [metadriverse/trafficgen#21]
I have download the shared model, and put it to the right path.(let init.ckpt to the path : /workspace/trafficgen/trafficgen/traffic_generator/ckpt/init.ckpt')

But I run the command, some thing is wrong:
```
# /workspace/trafficgen/trafficgen# python generate.py --gif 
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/trafficgen/trafficgen/traffic_generator/ckpt/act.ckpt'
```

**Comment by Alan-LanFeng** [comment]
Now 'act.ckpt' is uploaded.
