### ISSUE TITLE
Some questions about data and training

### ISSUE THREAD

**Issue by wjl2244** [metadriverse/trafficgen#25]
Hello, thank you very much for a meaningful job! I want to retrain this model, **first** I download all the 20s data from the `https://console.cloud.google.com/storage/browser/waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario/training_20s`, it has a total of 50 compressed files, I process it through the `sh utils/data_trans.sh PATH_A PATH_B ` script to produce a total of 3456 pkl files, However, you mentioned in the program comment that the number of files was 70542, may I ask if you only used `waymo training_20s data`?

**Secondly**, if I want to reproduce the results of the paper, do `init` and `act` models need to be trained separately? In the `Cluster Training` section of `README.md,` you only mentioned `python train_act.py`, do you need to run `python train_init.py`?

Looking forward to your reply and thanks again for your work!

**Comment by Alan-LanFeng** [comment]
Thanks for your question.

First: Yes, we only used 20s data.
Second: You need to train two models separately.

**Comment by LeonJoe13** [comment]
> Hello, thank you very much for a meaningful job! I want to retrain this model, **first** I download all the 20s data from the `https://console.cloud.google.com/storage/browser/waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario/training_20s`, it has a total of 50 compressed files, I process it through the `sh utils/data_trans.sh PATH_A PATH_B ` script to produce a total of 3456 pkl files, However, you mentioned in the program comment that the number of files was 70542, may I ask if you only used `waymo training_20s data`?
> 
> **Secondly**, if I want to reproduce the results of the paper, do `init` and `act` models need to be trained separately? In the `Cluster Training` section of `README.md,` you only mentioned `python train_act.py`, do you need to run `python train_init.py`?
> 
> Looking forward to your reply and thanks again for your work!

It seems that you didn't download all training_20s data，maybe only 50
