### ISSUE TITLE
Some questions about trainning

### ISSUE THREAD

**Issue by LeonJoe13** [metadriverse/trafficgen#26]
It's a very meaningful and exciting work!
I have several problems about cluster training
1. dataset
I download dataset from [https://console.cloud.google.com/storage/browser/waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario/training_20s?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false](url)
, which has 50 uncompressed files like 
![image](https://github.com/metadriverse/trafficgen/assets/95465194/dd1eabd8-8712-4218-bd99-a0996ba8d8de).
and I stored them in patha, then I run sh utils/data_trans.sh PATH_A PATH_B, terminal shows 
![image](https://github.com/metadriverse/trafficgen/assets/95465194/77c09cc1-2cfd-4416-a0f6-52cf516793dd)
But I get processed data in pathb like 
![image](https://github.com/metadriverse/trafficgen/assets/95465194/cdd97692-3738-49aa-9d55-8ffbf9a17780)
![image](https://github.com/metadriverse/trafficgen/assets/95465194/18994640-9127-417e-9dce-9f5660a250dc)
I'm not sure it 's right (I don't know what none_XX.pkl mean. and every time I run sh utils/data_trans.sh again, the total number is different.
2. Trainning
After I got processed data, I modify the 'data_path' in init/configs and act/configs to PATH_B:
![image](https://github.com/metadriverse/trafficgen/assets/95465194/86af027d-bb22-49b1-a916-867789b928b9),
run python init/uitls/init_dataset.py got error:
![image](https://github.com/metadriverse/trafficgen/assets/95465194/88313866-ef47-4f47-843b-91b628533e60)
could you tell me how to solve these problems? Thank you!

**Comment by Alan-LanFeng** [comment]
1. There are 1000 files in total. Make sure you download all of them


2. Adding this line of code in init_dataset.py can solve it.
from trafficgen.utils.typedef import AgentType, RoadEdgeType, RoadLineType

**Comment by LeonJoe13** [comment]
Thank for your reply! I have fixed above problems.

there is a new problem:

When I want to connect the generated scene with Metadrive, there is a error like:

![image](https://github.com/metadriverse/trafficgen/assets/95465194/c7de5e4a-acc0-4aa5-b7a1-e38621792e5c)

I have download the latest metadrive, it seems that the metadrive lack some keys for trafficgen,could you tell me how to solve?
many thanks!

**Comment by Alan-LanFeng** [comment]
MetaDrive now only supports Scenario Description, and we have planned to update trafficgen to support that format in the future.

**Comment by pengzhenghao** [comment]
Yes for reproducing result of TrafficGen we suggest stick to the old version of MetaDrive Best,ZhenghaoOn Aug 19, 2023, at 04:12, Alan ***@***.***> wrote:﻿
Closed #26 as completed.
