### ISSUE TITLE
Some questions about run_metadrive and run_rl_training

### ISSUE THREAD

**Issue by LeonJoe13** [metadriverse/trafficgen#29]
Thanks for your wonderful work!

I have a problem about how to link trafficgen-generated scene with metadrive

Key missing 
An error is displayed when running run_metadrive.py:
![image](https://github.com/metadriverse/trafficgen/assets/95465194/587db74a-a69a-4f7c-84f0-da03fb4875c9)
It seems that metadrive is not compatible with trafficgen.

I noticed another of your amazing work [ScenarioNet](https://github.com/metadriverse/scenarionet) and have been able to successfully visualize the waymo dataset on metadrive. What can I refer to about scenarionet ?

Thanks again for your great work!

**Comment by zhuhaozh** [comment]
Hi, @LeonJoe13 

Did you solve this problem? Could you share the version of MetaDrive you used?

**Comment by pengzhenghao** [comment]
Sorry for replying late. What issues we are encountering now?

**Comment by pengzhenghao** [comment]
Hi I have updated the code on run_metadrive.py
