### ISSUE TITLE
Question about duplicate vector assignment

### ISSUE THREAD

**Issue by nhendy** [metadriverse/trafficgen#31]
Hello team! Thanks for the great paper. I had a couple questions about the logic for selecting a vector for an agent. How do you currently handle having the same vector index mapped to multiple agents? It seems like the logic currently just selects the vector of min dist to the agent which could be used across multiple agents.

**Comment by Alan-LanFeng** [comment]
Hi, we currently do not handle this issue. The reason is that each vector represents a 5-meter center lane segment. And a vehicle's length is usually about 5 meters, so multiple vehicles within a vector are not common. If you still want to cope with this my suggestion is to reduce the length for each vector.

**Comment by nhendy** [comment]
Thanks so much for the reply! I have a couple follow ups. I wonder what about cases in junctions where there's a lot of overlapping vectors? and what about cases when the matched vector based on L2 distance is in the opposite direction in junctions? Currently there's a mask if the agent has a local yaw > 45 degrees but that would remove a lot of agents in junctions if they match to a vector that is in the opposite direction.

**Comment by Alan-LanFeng** [comment]
You're welcome! Your intuition is correct. In the junction, the vector could be mismatched. A better way to do this is to improve the matching method: for example, get several candidate vectors based on the L2 distance and then do the filtering.

**Comment by nhendy** [comment]
Thank you so much @Alan-LanFeng for the prompt responses! That answers my questions.
