### ISSUE TITLE
BCE loss used in masked agents prediction

### ISSUE THREAD

**Issue by nhendy** [metadriverse/trafficgen#33]
Hello team! I've been studying TrafficGen paper and implementation and I had a question about the task of training the model to predict missing agents. My understanding from the paper is that the task is similar to the MLM task in NLP where a token masked and the model is supervised to predict the missing token. However in the implementation it seems like we supervise the model for predicting masked and unmasked agents. I'm curious what your thoughts are behind that choice and if you had experience training TrafficGen to predict just the masked out agents. Thank you!

**Comment by Alan-LanFeng** [comment]
Hi,

sorry for the late response. For also predicting the unmasked agents, my thoughts are to imitate a simple auto-encoder, so that to accelerate the convergence. But it definitely worth doing more experiments on this. Interesting idea!
