### ISSUE TITLE
Connecting with the latest metadrive (0.4.1.2)

### ISSUE THREAD

**Issue by zhuhaozh** [metadriverse/trafficgen#35]
Hi, thanks for the awesome work. I'm current trying to follow [this instruction](https://github.com/metadriverse/trafficgen/tree/main#connect-trafficgen-with-metadrive) to connect trafficgen with metadrive, but something goes wrong with the latest metadrive. 

I found that the data structure are not the same as the latest version of metadrive.
The script `run_metadrive.py` works fine if I loaded waymo dataset in metadrive, but the map cannot be properly loaded using the generated dataset, such as vehicle length is missing, empty lanes, etc. 

So, is there any plan to upgrade the current version to support the latest metadrive? Or where can i find relevant documents?

**Comment by zhuhaozh** [comment]
Partially solved by adding "LANE_CENTER_LINE" to `is_lane` method:
in metadrive/type.py: 
```python
    @classmethod
    def is_lane(cls, type):
        return type in [cls.LANE_SURFACE_STREET, cls.LANE_FREEWAY, cls.LANE_BIKE_LANE, cls.LANE_CENTER_LINE]

```

The lanes can be loaded by adding `cls.LANE_CENTER_LINE` but i'm not sure if this generates correct maps. 

There still seem to be a lot of differences between trafficgen and metadrive's data structures, e.g. traffic lights.

**Comment by Alan-LanFeng** [comment]
Sorry for the late response. We are planning to solve the data format problem in the next version of TrafficGen, in which we are using scenarionet format data.
