### ISSUE TITLE
Some question about run_metadrive.py

### ISSUE THREAD

**Issue by AntaiXie** [metadriverse/trafficgen#39]
Thank you for sharing this nice work!
Recently, I encountered some problems while replicating your paper on the training of reinforcement learning agents in trafficgen. I hope you can answer them.
1.Here is error messgage:
[INFO] MetaDrive version: 0.4.1.2
[INFO] Sensors: [lidar: Lidar(50,), side_detector: SideDetector(), lane_line_detector: LaneLineDetector()]
[INFO] Render Mode: none
Episode:   0%|          | 0/100 [00:00<?, ?it/s][INFO] Assets version: 0.4.1.2
Episode:   0%|          | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Code\trafficgen\trafficgen\run_metadrive.py", line 63, in <module>
    env.reset()
  File "D:\Code\trafficgen\metadrive\envs\base_env.py", line 492, in reset
    self.lazy_init()  # it only works the first time when reset() is called to avoid the error when render
  File "D:\Code\trafficgen\metadrive\envs\base_env.py", line 377, in lazy_init
    self.setup_engine()
  File "D:\Code\trafficgen\metadrive\envs\scenario_env.py", line 151, in setup_engine
    self.engine.register_manager("data_manager", ScenarioDataManager())
  File "D:\Code\trafficgen\metadrive\manager\scenario_data_manager.py", line 36, in __init__
    self.summary_dict, self.summary_lookup, self.mapping = read_dataset_summary(self.directory)
  File "D:\Code\trafficgen\metadrive\scenario\utils.py", line 378, in read_dataset_summary
    summary_dict = {f: read_scenario_data(os.path.join(file_folder, f))["metadata"] for f in files}
  File "D:\Code\trafficgen\metadrive\scenario\utils.py", line 378, in <dictcomp>
    summary_dict = {f: read_scenario_data(os.path.join(file_folder, f))["metadata"] for f in files}
KeyError: 'metadata'
Is this a problem with the metadrive version? Which version should I download to reproduce your article?
2.I see that the data used in your code is a 20s segment, so the environment for reinforcement learning agent training is also 20s per scenario, right? Can we achieve a longer time frame because I feel that the training for reinforcement learning in 20s is too short

**Comment by Alan-LanFeng** [comment]
Hi, 
thanks for asking.

@QuanyiLi Can you help with this?

2. Indeed, we use 20s data for training the RL agent. It can be longer, but you need to pay attention to two things a. traffic light. b. agents will typically drive out of the map after 20s.

**Comment by QuanyiLi** [comment]
Hi,

We recently wrapped and released all data process tools via ScenarioNet. Thus the latest MetaDrive is updated to be compatible with ScenarioNet. If the waymo data is processed with ScenarioNet, it should be fine to work with MetaDrive. If it is processed with tools in TrafficGen repo, it is expected to encounter some errors when loading scenarios to latest MetaDrive. In this case, a solution could be to lower the MetaDrive version via `pip install MetaDrive==0.3.0.1 `

**Comment by pengzhenghao** [comment]
Hi, I fixed the issue with latest metadrive. Please pull TrafficGen and see if everything work. Please feel free to inform me the result and reopen the issue. Thanks!
