### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'items'

### ISSUE THREAD

**Issue by axelbr** [metadriverse/trafficgen#41]
There are some type bugs when running `python train_act.py -c local `.

I get an attribute error in the tg_act.py file. For instance in this line (and several other occasions):
https://github.com/metadriverse/trafficgen/blob/33b57467c3d0bb31b8393998057c67df2aebc550/trafficgen/act/model/tg_act.py#L105

It looks like that the loss tensor used instead of `loss_dict`.

**Comment by PabloVD** [comment]
It also happened to me. It seems that replacing ` loss.items()` by ` loss_dict.items()` fixed the bug.
