### ISSUE TITLE
Question about train dataset and test dataset split

### ISSUE THREAD

**Issue by nemonswx** [metadriverse/trafficgen#42]
In the paper, you mentioned '(70000 scenarios after filtering) are further split into a training dataset (50,000 cases) and a non-overlapping test dataset (1,000 cases).' However, I did not see the how you did it in 'init_dataset.py' and 'act_dataset.py'. So how exactly did you split these scenarios?

**Comment by Alan-LanFeng** [comment]
Hi, we manually split the data into different folders in advance.
