### ISSUE TITLE
Version number of "metadrive-simulator" missing from requirements.txt

### ISSUE THREAD

**Issue by AdityaWadhwa** [metadriverse/trafficgen#44]
I am following the readme to try to use the tool. The requirements do not specify any specific version of the "metadrive-simulator", so I got the latest one. The step that uses the "run_metadrive.py" file does not work for me. The reason is that WaymoEnv is no longer there in the latest version. Please put the exact version number in the requirements file.

https://github.com/metadriverse/trafficgen/blob/main/trafficgen/run_metadrive.py#L14

**Comment by pengzhenghao** [comment]
I have fixed this with latest metadrive and trafficgen. Thanks!
