### ISSUE TITLE
python generate.py --save_metadrive

### ISSUE THREAD

**Issue by FrankSinatral** [metadriverse/trafficgen#46]
<img width="2263" alt="Screenshot 2024-05-07 at 15 41 13" src="https://github.com/metadriverse/trafficgen/assets/99521814/235ec1c9-dc87-42a1-9042-f6df1118679d">
Thanks for your work, when I try to use save_metadrive and run the above code in terminal I encountered with the problem in this picture, I am wondering which meta drive version you are using, I just run pip install meta drive to use this package.

**Comment by pengzhenghao** [comment]
Hi, I fixed the issue with latest metadrive. Please pull TrafficGen and see if everything work. Please feel free to inform me the result and reopen the issue. Thanks!
