### ISSUE TITLE
Loading scenarios pikle in metradrive

### ISSUE THREAD

**Issue by Sterley** [metadriverse/trafficgen#47]
Hi guys, When I tried to load scenarios using this scenarios pickle files : https://github.com/metadriverse/trafficgen/blob/main/trafficgen/dataset/README.md
using this version of metadrive at this commit : b58863f13354fb055663f09b21e110017ddc22ae
and using this script : https://github.com/metadriverse/trafficgen/blob/main/trafficgen/run_metadrive.py

I have this type of error in the screenshot, I cant really understand the source of this error. Please help me ! Thank you !

![Screenshot from 2024-05-06 15-11-06](https://github.com/metadriverse/trafficgen/assets/43834576/789e0671-30ab-46eb-b9c5-83f77259dd62)
![Screenshot from 2024-05-06 15-11-27](https://github.com/metadriverse/trafficgen/assets/43834576/5ab03b1a-28c3-4a5e-8ab1-de87ae983edb)

**Comment by pengzhenghao** [comment]
Hi, I fixed the issue with latest metadrive. Please pull TrafficGen and see if everything work. Please feel free to inform me the result and reopen the issue. Thanks!
