### ISSUE TITLE
 Clarification on data['agent'] Feature Details in train_act.py

### ISSUE THREAD

**Issue by zywangEcho** [metadriverse/trafficgen#51]
Hello,

First of all, thank you for your excellent work on this project. I am currently working with the train_act.py file and have a question regarding the input data for the act model.

In my setup, the feature size of data['agent'] is (128, 32, 8), where:

128 refers to the batch size,
32 refers to the maximum number of agents,
8 refers to the motion features.
I would like to know what these 8 specific motion features represent. Could you please provide some details or point me to the relevant section of the documentation/code where I can find this information?

I read act_dataset.py, I guess maybe it present "x, y, vx, vy, heading, length, width, valid". However, when I extract data['agent'][0,0,:],it give me [0,0,0.32,-5.16e-04,1,0,5.286, 2.332], It looks like I might have misunderstood the meaning of the code.

Thank you very much for your assistance.

**Comment by Alan-LanFeng** [comment]
Hi,

They are self.position, self.velocity, self.heading, self.length_width.

which means x,y,vx,vy,cos(heading), sin(heading), length,width
