### ISSUE TITLE
init_dataset.py error

### ISSUE THREAD

**Issue by Sterley** [metadriverse/trafficgen#52]
![Capture d'écran 2024-07-09 161454](https://github.com/metadriverse/trafficgen/assets/43834576/02f5e5c7-dfcc-4356-9134-9b83d2a14cf3)

Hello,

I have processed the data in  : **waymo_open_dataset_motion_v_1_1_0/uncompressed/scenario/training_20**s
using this command ligne : **python trafficgen/scripts/trans20.py PATH_A PATH_B None**

When I launch the script init_dataset.py using the processed data in PATH_B. I have the error in the screenshot. I dont really understand why.

Would you help me please?

Thank you

**Comment by Alan-LanFeng** [comment]
Hi, it is because of your working directory. You can try to run the script in different directories to solve this.

**Comment by Sterley** [comment]
Hello,
I have moved them to sample_data and use the same configuration as you. I still have the same bug.

**Comment by Sterley** [comment]
Hello,
I solved the bug by adding this line to the file :
from trafficgen.utils.typedef import AgentType, RoadLineType, RoadEdgeType

thank you
