### ISSUE TITLE
Inquiry Regarding Input Data and Initialization Model Implementation

### ISSUE THREAD

**Issue by jeromefan** [metadriverse/trafficgen#53]
Hello,

Firstly, I would like to express my appreciation for the outstanding work you have shared. I have a few queries concerning the input data and the implementation of the initialization model.

1. **Understanding the Processed Data Structure:**
   I have examined the `parse_data()` function in `trafficgen/scripts/trans20.py`, which provided clarity on the values within `0.pkl`, including `all_agent` and others. However, the `InitDataset` utilized in `class TrafficGen` processes `0.pkl` through the `process_data_to_internal_format` function, yielding new data with keys such as 

   ```dict_keys(['agent', 'agent_mask', 'center', 'center_mask', 'bound', 'bound_mask', 'cross', 'cross_mask', 'rest', 'rest_mask', 'vec_based_rep', 'agent_vec_index', 'agent_feat', 'lane_inp', 'lane_mask', 'gt_bbox', 'gt_distribution', 'gt_long_lat', 'gt_speed', 'gt_vel_heading', 'gt_heading', 'other']).```

    Could you please elucidate the precise meaning of these keys and the elements they encompass? Especially the value used in the function `inference()` of `class initializer`.

2. **Generating New Traffic Scenarios:**
   As per your paper, "After training, TrafficGen takes m as input and generates tau' as a totally different scenario." Could you provide guidance on only the HD map as input, without the inclusion of any vehicles. How is this accomplished?

3. **Context Vector Usage:**
   In the `class initializer`, there are two `class CG_stacked`: `self.CG_agent` and `self.CG_line`. Additionally, within the `forward()` function, the following operations are performed:

   ```python
   context_agent = self.agent_feature_extract(data['agent_feat'], data['agent_mask'], random_mask)
   feature = self.map_feature_extract(data['lane_inp'], data['lane_mask'], context_agent)
   ```

   The `agent_feature_extract` function takes `agent_feat` and creates an all-one vector as the context vector `c`, then generates an updated context vector `c'`. This `c'` is subsequently used in `map_feature_extract` to produce `line_enc` and `context_line`, and somehow obtain the `feature` by concate these two variable. I am somewhat perplexed by this approach, as it seems to diverge from the description in your paper. Could you offer some insight to help me comprehend this design choice?

Thank you very much for your valuable assistance.

**Comment by Alan-LanFeng** [comment]
1. 'agent' means vehicle states. ; center/bound/etc mean map states; 'vec_based_rep' means agent states in the map vector coordinates
2. During training and inference, you can use a random initialized embedding to represent that the map is empty.
3. Concatenating features is like doing the residual connection. The CG encoder takes a context embedding as input so at the very beginning the context should be all one. You can refer to multipath++ for this part.
