### ISSUE TITLE
TrafficGen Input  without Agents

### ISSUE THREAD

**Issue by yusufM03** [metadriverse/trafficgen#58]
Hi,
Is there a way to generate Scenarios with only Map features as Input ? 
Because according to the code , the vehicle's placement model depends on existing agent with the map .

Thank you

**Comment by pengzhenghao** [comment]
This is a long lasting problem and according to some feedback from other user I believe it's not trivial modification to make it work without the first agent. That can be considered to be a limitation of this work. Sorry for this. I remember a paper citing TrafficGen talked about this but unfortunately I can't find it out.

The intuition behind this is that the first agent's velocity actually makes a strong prior knowledge to other agents.
